version: "3.9"

services:
  gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile.gateway
    environment:
      - LITCOACH_MOCK=true
      - GATEWAY_HOST=0.0.0.0
      - GATEWAY_PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data

