name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
          pip install -e .
      - name: Run tests
        env:
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: '1'
        run: pytest -p pytest_cov

  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build sdist and wheel
        run: |
          python -m pip install --upgrade pip build
          python -m build
      - name: Publish to PyPI
        if: secrets.PYPI_API_TOKEN != ''
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: OpenGov-Literacy Coach ${{ github.ref_name }}
          body_path: docs/RELEASE_NOTES_${{ github.ref_name }}.md
          files: |
            dist/*.whl
            dist/*.tar.gz
      - name: Log in to Docker Hub
        if: secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != ''
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        if: secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != ''
        run: |
          docker compose build
          # Example: docker tag literacy-coach-gateway ${{ secrets.DOCKERHUB_USERNAME }}/literacy-coach-gateway:${GITHUB_REF_NAME}
          # Example: docker push ${{ secrets.DOCKERHUB_USERNAME }}/literacy-coach-gateway:${GITHUB_REF_NAME}
